services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: turn_tracker_pro
      POSTGRES_PASSWORD: "sFpwjL8EEXd9UKh2ttW-Xoi-YWkaqKQg"
    volumes:
      - turn_tracker_pro_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "-ioOBPL23AZ-raE_tLUtkZFKo7KIQ3QA"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: turn_tracker_pro_test
      POSTGRES_PASSWORD: "71SeLOIyCk_r-3ChN2Uu9uR-SNoXonhh"
    volumes:
      - turn_tracker_pro_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "rUQUKL3fs_5KIAcCmJrcxKHtmH95MtV1"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  turn_tracker_pro_data:
  turn_tracker_pro_test_data:
